#!/bin/bash
staged=$(git diff --cached --name-only --diff-filter=d -- "*.json" "*.gradle" "*.java")
if [ "$staged" = "" ]; then
    echo "No JSON, Gradle, or Java code to reformat"
    exit 0
fi

# Format the code and re-add changes if it was successful
gradle spotlessApply
if [ "$?" = "0" ]; then
    git add $staged
else
    exit 1
fi