
# BUILT-IN SIGNAL HANDLER CHANNELS

const CAN_CROSS_BORDER_CHANNEL* = "CanCrossBorder"
const ABILITY_CLICKED_CHANNEL* = "AbilityClicked"
const GET_ABILITY_COORD_TARGETS_CHANNEL* = "GetAbilityCoordTargets"
const GET_STATS_CHANNEL* = "GetStats"