package net.lugocorp.kingdom.ai;

/**
 * Decisions are generated by the AI's Goals so that it can decide what to do
 * for each DecisionChannel
 */
public class Decision {
    public final DecisionChannel channel;
    public final Priority priority;
    public final Behavior behavior;

    public Decision(DecisionChannel channel, Priority priority, Behavior behavior) {
        this.channel = channel;
        this.priority = priority;
        this.behavior = behavior;
    }
}
